version: 0
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Env Running
          command: echo Circle CI says 'Hello'.
      - run:
          name: Date
          command: date